# Generated by Django 6.0.6 on 2026-07-07 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultad',
            options={},
        ),
        migrations.AlterField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.facultad'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Malla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año del Plan')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mallas', to='academico.carrera', verbose_name='Carrera')),
                ('materias', models.ManyToManyField(related_name='mallas', to='academico.materia', verbose_name='Materias de la Malla')),
            ],
            options={
                'verbose_name': 'Malla Curricular',
                'verbose_name_plural': 'Mallas Curriculares',
            },
        ),
        migrations.DeleteModel(
            name='MallaCurricular',
        ),
    ]
